spring.application.name=change_tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/cdc_test
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update