spring.application.name=change_tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/cdc_test
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Auto SQL Schema Init for missing columns
spring.sql.init.mode=always

# Keycloak Güvenlik Ayarları
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/change-tracker-realm

# Uygulama Kimlik Bilgileri (Client ID ve kopyaladığın gizli şifre)
spring.security.oauth2.client.registration.keycloak.client-id=change-tracker-client
spring.security.oauth2.client.registration.keycloak.client-secret=E5JuBmbRoMQYpSjPIBEq87Iha1P84cubR1zm1kQuEYRJngPkmOKN6evVeCFkNxbIYMVD3TVdkB5fu0zxVXNze4
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid